/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademicIntegrityRouteImport } from './routes/academic-integrity'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTopicGeneratorRouteImport } from './routes/_authenticated/topic-generator'
import { Route as AuthenticatedThesesRouteImport } from './routes/_authenticated/theses'
import { Route as AuthenticatedQuickProposalRouteImport } from './routes/_authenticated/quick-proposal'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as AuthenticatedNewThesisRouteImport } from './routes/_authenticated/new-thesis'
import { Route as AuthenticatedMyTopicsRouteImport } from './routes/_authenticated/my-topics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedThesisIdRouteImport } from './routes/_authenticated/thesis/$id'
import { Route as AuthenticatedProposalIdRouteImport } from './routes/_authenticated/proposal/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicIntegrityRoute = AcademicIntegrityRouteImport.update({
  id: '/academic-integrity',
  path: '/academic-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTopicGeneratorRoute =
  AuthenticatedTopicGeneratorRouteImport.update({
    id: '/topic-generator',
    path: '/topic-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedThesesRoute = AuthenticatedThesesRouteImport.update({
  id: '/theses',
  path: '/theses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickProposalRoute =
  AuthenticatedQuickProposalRouteImport.update({
    id: '/quick-proposal',
    path: '/quick-proposal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewThesisRoute = AuthenticatedNewThesisRouteImport.update({
  id: '/new-thesis',
  path: '/new-thesis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyTopicsRoute = AuthenticatedMyTopicsRouteImport.update({
  id: '/my-topics',
  path: '/my-topics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThesisIdRoute = AuthenticatedThesisIdRouteImport.update({
  id: '/thesis/$id',
  path: '/thesis/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalIdRoute = AuthenticatedProposalIdRouteImport.update({
  id: '/proposal/$id',
  path: '/proposal/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-integrity': typeof AcademicIntegrityRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-topics': typeof AuthenticatedMyTopicsRoute
  '/new-thesis': typeof AuthenticatedNewThesisRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/quick-proposal': typeof AuthenticatedQuickProposalRoute
  '/theses': typeof AuthenticatedThesesRoute
  '/topic-generator': typeof AuthenticatedTopicGeneratorRoute
  '/proposal/$id': typeof AuthenticatedProposalIdRoute
  '/thesis/$id': typeof AuthenticatedThesisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-integrity': typeof AcademicIntegrityRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-topics': typeof AuthenticatedMyTopicsRoute
  '/new-thesis': typeof AuthenticatedNewThesisRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/quick-proposal': typeof AuthenticatedQuickProposalRoute
  '/theses': typeof AuthenticatedThesesRoute
  '/topic-generator': typeof AuthenticatedTopicGeneratorRoute
  '/proposal/$id': typeof AuthenticatedProposalIdRoute
  '/thesis/$id': typeof AuthenticatedThesisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academic-integrity': typeof AcademicIntegrityRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-topics': typeof AuthenticatedMyTopicsRoute
  '/_authenticated/new-thesis': typeof AuthenticatedNewThesisRoute
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/quick-proposal': typeof AuthenticatedQuickProposalRoute
  '/_authenticated/theses': typeof AuthenticatedThesesRoute
  '/_authenticated/topic-generator': typeof AuthenticatedTopicGeneratorRoute
  '/_authenticated/proposal/$id': typeof AuthenticatedProposalIdRoute
  '/_authenticated/thesis/$id': typeof AuthenticatedThesisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-integrity'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/my-topics'
    | '/new-thesis'
    | '/proposals'
    | '/quick-proposal'
    | '/theses'
    | '/topic-generator'
    | '/proposal/$id'
    | '/thesis/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-integrity'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/my-topics'
    | '/new-thesis'
    | '/proposals'
    | '/quick-proposal'
    | '/theses'
    | '/topic-generator'
    | '/proposal/$id'
    | '/thesis/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academic-integrity'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-topics'
    | '/_authenticated/new-thesis'
    | '/_authenticated/proposals'
    | '/_authenticated/quick-proposal'
    | '/_authenticated/theses'
    | '/_authenticated/topic-generator'
    | '/_authenticated/proposal/$id'
    | '/_authenticated/thesis/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademicIntegrityRoute: typeof AcademicIntegrityRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-integrity': {
      id: '/academic-integrity'
      path: '/academic-integrity'
      fullPath: '/academic-integrity'
      preLoaderRoute: typeof AcademicIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/topic-generator': {
      id: '/_authenticated/topic-generator'
      path: '/topic-generator'
      fullPath: '/topic-generator'
      preLoaderRoute: typeof AuthenticatedTopicGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/theses': {
      id: '/_authenticated/theses'
      path: '/theses'
      fullPath: '/theses'
      preLoaderRoute: typeof AuthenticatedThesesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-proposal': {
      id: '/_authenticated/quick-proposal'
      path: '/quick-proposal'
      fullPath: '/quick-proposal'
      preLoaderRoute: typeof AuthenticatedQuickProposalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-thesis': {
      id: '/_authenticated/new-thesis'
      path: '/new-thesis'
      fullPath: '/new-thesis'
      preLoaderRoute: typeof AuthenticatedNewThesisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-topics': {
      id: '/_authenticated/my-topics'
      path: '/my-topics'
      fullPath: '/my-topics'
      preLoaderRoute: typeof AuthenticatedMyTopicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/thesis/$id': {
      id: '/_authenticated/thesis/$id'
      path: '/thesis/$id'
      fullPath: '/thesis/$id'
      preLoaderRoute: typeof AuthenticatedThesisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposal/$id': {
      id: '/_authenticated/proposal/$id'
      path: '/proposal/$id'
      fullPath: '/proposal/$id'
      preLoaderRoute: typeof AuthenticatedProposalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyTopicsRoute: typeof AuthenticatedMyTopicsRoute
  AuthenticatedNewThesisRoute: typeof AuthenticatedNewThesisRoute
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedQuickProposalRoute: typeof AuthenticatedQuickProposalRoute
  AuthenticatedThesesRoute: typeof AuthenticatedThesesRoute
  AuthenticatedTopicGeneratorRoute: typeof AuthenticatedTopicGeneratorRoute
  AuthenticatedProposalIdRoute: typeof AuthenticatedProposalIdRoute
  AuthenticatedThesisIdRoute: typeof AuthenticatedThesisIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyTopicsRoute: AuthenticatedMyTopicsRoute,
  AuthenticatedNewThesisRoute: AuthenticatedNewThesisRoute,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedQuickProposalRoute: AuthenticatedQuickProposalRoute,
  AuthenticatedThesesRoute: AuthenticatedThesesRoute,
  AuthenticatedTopicGeneratorRoute: AuthenticatedTopicGeneratorRoute,
  AuthenticatedProposalIdRoute: AuthenticatedProposalIdRoute,
  AuthenticatedThesisIdRoute: AuthenticatedThesisIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademicIntegrityRoute: AcademicIntegrityRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
